# Generated by Django 5.0.1 on 2024-01-29 23:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IA', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='image',
            field=models.CharField(default='default.png', max_length=50),
        ),
        migrations.AddField(
            model_name='card',
            name='serial',
            field=models.CharField(default='WE-000.001', max_length=20),
        ),
        migrations.AddField(
            model_name='card',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='card',
            name='category',
            field=models.CharField(choices=[('Weapon', 'Option1'), ('Potion', 'Option2'), ('Armor', 'Option3')], default='Weapons', max_length=20),
        ),
        migrations.AlterField(
            model_name='card',
            name='description',
            field=models.CharField(max_length=500),
        ),
    ]
